DROP TABLE IF EXISTS AUTHORS;
CREATE TABLE AUTHORS(ID BIGINT PRIMARY KEY, NAME VARCHAR(255) NOT NULL);

DROP TABLE IF EXISTS GENRES;
CREATE TABLE GENRES(ID BIGINT PRIMARY KEY, NAME VARCHAR(255) NOT NULL);

DROP TABLE IF EXISTS BOOKS;
CREATE TABLE BOOKS(ID BIGINT PRIMARY KEY, TITLE VARCHAR(255) NOT NULL, GENRE_ID BIGINT, AUTHOR_ID BIGINT, ISBN VARCHAR(255));
ALTER TABLE BOOKS ADD FOREIGN KEY(GENRE_ID) REFERENCES GENRES(ID) ON DELETE RESTRICT;
ALTER TABLE BOOKS ADD FOREIGN KEY(AUTHOR_ID) REFERENCES AUTHORS(ID) ON DELETE RESTRICT;

DROP SEQUENCE IF EXISTS S_AUTHORS;
CREATE SEQUENCE S_AUTHORS START WITH 1000;

DROP SEQUENCE IF EXISTS S_GENRES;
CREATE SEQUENCE S_GENRES START WITH 1000;

DROP SEQUENCE IF EXISTS S_BOOKS;
CREATE SEQUENCE S_BOOKS START WITH 1000;