application:
  filepath: questions_sample.csv
  locale: en
exam:
  passagePercent: 60
  questionNumber: 5
spring:
  shell:
    interactive:
      enabled: true
  main:
    allow-circular-references: true
    web-application-type: none
  messages:
    basename: messages
logging:
  level:
    root: ERROR