spring:
  shell:
    interactive:
      enabled: true
  main:
    allow-circular-references: true
    allow-bean-definition-overriding: true
  data:
    mongodb:
      database: library
      port: 27017
      host: localhost
logging:
  level:
    root: ERROR
mongock:
  runner-type: "InitializingBean"
  change-logs-scan-package:
    - ru.otus.spring.library.mongock