spring:
  shell:
    interactive:
      enabled: true
  main:
    allow-circular-references: true
  datasource:
    url: jdbc:h2:mem:testdb
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
  sql:
    init:
      mode: always
      data-locations: data.sql
      schema-locations: schema.sql
  h2:
    console:
      path: /h2-console
      enabled: true
      settings:
        web-allow-others: true
  data:
    mongodb:
      database: library2
      port: 27017
      host: localhost
logging:
  level:
    root: INFO