version: '1'
services:
  nginx:
    container_name: nginx
    image: nginx:1.22.1
    restart: always
    ports:
      - 80:80
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
  library:
    container_name: lib-app
    image: library-image:latest
    environment:
      - "SERVER_PORT=8080"
    expose:
       - "8080"
    depends_on:
      - nginx
    restart: always

