drop table if exists SCHEDULES CASCADE;
drop table if exists TASKS CASCADE;
drop sequence if exists s_SCHEDULES;
drop sequence if exists s_TASKS;
create sequence s_SCHEDULES start with 1 increment by 50;
create sequence s_TASKS start with 1 increment by 50;
create table SCHEDULES (id bigint not null, name varchar(255), seconds bigint, primary key (id));
create table TASKS (id bigint not null, code varchar(255), name varchar(255), next_run timestamp, schedule_id bigint, primary key (id));
alter table TASKS add constraint fk_TASKS_SCHEDULES foreign key (schedule_id) references SCHEDULES;
commit;